### ISSUE TITLE
疑问？

### ISSUE THREAD

**Issue by pyz610173878** [obgnail/share-clipboard#1]
您好JavaScript 能否实现类似于微信输入法中的跨平台剪切板共享，他与 go语言实现有很大的区别吗？

**Comment by obgnail** [comment]
@pyz610173878 

1. 原理上肯定能实现的。但是大概率很麻烦，具体的麻烦程度要看你的需求。
2. 剪切板共享无非就两种方案，peer-peer 或者 peer-server-peer。前者要求设备同处一个网络，后者要求有一个服务器，如果是内网服务器还要做内网穿透。
3. 如果是 PC 之间共享的话，麻烦程度还不太高。每次开机系统自动开启一个后台服务即可。
4. 如果需要和手机共享的话，你还要专门做一个 APP，现在安卓已经收紧政策，不再允许后台读取剪切板了。所以每当你想共享的时候，要打开 APP，找到你的设备，共享……每次都得穿鞋戴帽，一套流程下来，费时又费力。如果是苹果的话，还要上架 AppStore……
5. 上面说的还只是共享纯文本的情况，如果还要共享剪切板里的图片、文件等数据，那你还得学习一下各个操作系统的相关 API

总结，自己做一个共享剪切板软件会很麻烦，虽然不至于做不了，简单做做出来的也大概率是个玩具。使用现成的成熟产品更加实际一些。现在各家手机厂商都在做生态，碰一碰就能共享什么的应该是基操，直接用就是了。

PS：小众上还是有不少类似产品的：[小众软件](https://www.appinn.com/tag/%E5%89%AA%E8%B4%B4%E6%9D%BF/)，找一个喜欢的用用就行了。

**Comment by pyz610173878** [comment]
谢谢前辈解答。我的出发点为：利用前端知识解决自己生活中出现的问题，一来可以提高效率和培训兴趣，二来可以作为自己的独立的项目。类似于您的 Typora 插件。您的仓库给了我很多启发。谢谢！

**Comment by obgnail** [comment]
@pyz610173878 

如果是这种情况的话，你可以用 nodeJS 做一个自用的，适用于 PC 的 共享剪切板 项目。
> 浏览器环境下，JS 非常受限，很多功能都实现不了，建议还是在 node 里实现。

1. 网络通讯方面。如果你了解计算机网络，可以基于 tcp 自定义通讯协议；如果不太了解，可以直接使用 http 通讯
2. 操作剪切板方面，因为涉及操作系统的api，建议还是使用现成的 node 剪切板相关库

你甚至可以将上面的逻辑做成 typora 插件。当你的两台电脑打开 typora 后，就可以互相通讯，共享剪切板。

typora 插件同时拥有 browser 和 node 两套环境，
优点是拥有丰富的轮子，node环境负责具体的服务，browser环境做点简单的弹窗。有兴趣的话甚至可以做成一个轻量级的 qq，在 typora 里聊天什么的。
缺点就是不太好调试。
